"""'db_creation'

Revision ID: afa2d8935862
Revises: 
Create Date: 2024-05-27 17:45:08.978103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa2d8935862'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_notice',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accouting_notice',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_type', sa.Integer(), nullable=False),
                    sa.Column('id_user', sa.String(), nullable=False),
                    sa.Column('text', sa.String(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('date_birthday', sa.Date(), nullable=True),
                    sa.Column('date_notice', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['id_type'], ['type_notice.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accouting_notice')
    op.drop_table('type_notice')
    # ### end Alembic commands ###
